### ISSUE TITLE
How do you actually draw the lines?

### ISSUE THREAD

**Issue by abitrolly** [idank/showthedocs#4]
I must say this is very impressive. 

![image](https://github.com/idank/showthedocs/assets/8781107/e4dbd024-f646-4fdb-96b6-9d7fb685eb78)

Especially for 8 y/o project.

While trying to wrap my head around HTML layouts, I found it extremely difficult to reason about position of elements on the page. Here you not only know the positions, but also draw the lines across different blocks to connect them. How do you do this?

**Comment by idank** [comment]
Whoa it's been a while since I've looked at the code here!

I believe it's all based on https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect and then some SVG stuff to draw things on the page.

**Comment by abitrolly** [comment]
Makes sense. Thanks!
